### ISSUE TITLE
Drcom 更新心跳包

### ISSUE THREAD

**Issue by Maalau** [GJXS1980/ODP#2]
Drcom 更新心跳包 dalao能否出个更新 或者可以指引一下 怎么把心跳包改到最新的里面  烦扰了
根据抓包教程 网页转化出来心跳包如下
server = '10.0.3.2'
pppoe_flag = '\x2f'
keep_alive2_flag = '\xdc'

**Comment by GJXS1980** [comment]
> Drcom 更新心跳包 dalao能否出个更新 或者可以指引一下 怎么把心跳包改到最新的里面 烦扰了
> 根据抓包教程 网页转化出来心跳包如下
> server = '10.0.3.2'
> pppoe_flag = '\x2f'
> keep_alive2_flag = '\xdc'

ODP/files/etc/config/gdut_drcom和ODP/files/etc/gdut-drcom.conf
